services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000  # Comando explícito
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8001:8000"  # Usa el puerto estándar (cambia solo si es necesario)
    env_file:
      - .env.dev  # Asegúrate de que coincida con las credenciales de 'db'
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: devuser  # Debe coincidir con DB_USER en .env.dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen persistente
    ports:
      - "5432:5432"  # Opcional: Expone PostgreSQL para herramientas externas (ej: DBeaver)

volumes:
  postgres_data:  # Define el volumen para la DB
