services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn mi_proyecto.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.prod
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpass-ultra-segura
      POSTGRES_DB: dbprod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U produser -d dbprod"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - ./certs:/etc/letsencrypt #for ssl certifiactes
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
