# Generated by Django 4.2 on 2025-07-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsupplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_score', models.FloatField(default=0.0)),
                ('delivery_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('supplier_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='productsupplier.supplierproduct')),
            ],
            options={
                'verbose_name': 'Supplier Product Score',
                'verbose_name_plural': 'Supplier Product Scores',
            },
        ),
    ]
