# Generated by Django 4.2 on 2025-07-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsupplier', '0002_supplierproductscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierproductscore',
            options={},
        ),
        migrations.RenameField(
            model_name='supplierproductscore',
            old_name='delivery_score',
            new_name='quantity_score',
        ),
    ]
