# Generated by Django 4.2 on 2025-07-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsupplier', '0003_alter_supplierproductscore_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='purchase_unit',
            new_name='min_order_quantity',
        ),
    ]
