# Generated by Django 4.2 on 2025-06-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('credit_score', models.FloatField(default=0.0)),
                ('cost_delivery_score', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
