# Generated by Django 4.2 on 2025-07-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='overall_score',
            field=models.FloatField(default=0.0),
        ),
    ]
