# Generated by Django 4.2 on 2025-07-27 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0002_supplier_overall_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cost_delivery_score',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_score',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='overall_score',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='reliability_score',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
