# Generated by Django 4.2 on 2025-07-27 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0003_alter_supplier_cost_delivery_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='overall_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
