# Generated by Django 4.2 on 2025-07-29 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0005_alter_supplier_cost_delivery_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='credit_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
