# Generated by Django 4.2 on 2025-08-01 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0006_supplier_credit_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='deleivery_cost',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cost_delivery_score',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_score',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='reliability_score',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
