# Generated by Django 4.2 on 2025-08-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0007_supplier_deleivery_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='deleivery_cost',
            new_name='delivery_cost',
        ),
    ]
