# Generated by Django 4.2 on 2025-09-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0008_rename_deleivery_cost_supplier_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
