# Generated by Django 4.2 on 2025-06-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
