# Generated by Django 4.2 on 2025-06-29 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_inventoryitem_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('ordered', 'Ordered'), ('received', 'Received in Warehouse'), ('quality_check', 'Quality Check'), ('ready_for_sale', 'Ready for Sale'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('discarded', 'Discarded')], max_length=20)),
                ('new_status', models.CharField(choices=[('ordered', 'Ordered'), ('received', 'Received in Warehouse'), ('quality_check', 'Quality Check'), ('ready_for_sale', 'Ready for Sale'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('discarded', 'Discarded')], max_length=20)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status Change Log',
                'verbose_name_plural': 'Status Change Logs',
                'ordering': ['-change_date'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['current_status'], name='inventory_i_current_8badba_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['status_changed'], name='inventory_i_status__2f71d8_idx'),
        ),
        migrations.AddField(
            model_name='statuschangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statuschangelog',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='inventory.inventoryitem'),
        ),
    ]
