# Generated by Django 4.2 on 2025-06-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_statuschangelog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
